name: Prerelease
description: Create a prerelease pull requests and prereleases

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".release-please-manifest.json"
      - "CHANGELOG.md"

permissions:
  contents: write
  pull-requests: write
  packages: read # Required to pull docker image from ghcr.io

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Bootstrap Release PR
        uses: docker://ghcr.io/google-github-actions/release-please-action:v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          entrypoint: release-please
          args: >
            release-pr
            --config-file=prerelease-please-config.json
            --manifest-file=.release-please-manifest.json
            --repo-url=${{ github.repository }}