name: Prerelease
description: Create a prerelease pull requests and prereleases

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".release-please-manifest.json"
      - "CHANGELOG.md"

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please Prerelease
        uses: google-github-actions/release-pr@v4
        with:
          config-file: prerelease-please-config.json
          manifest-file: .release-please-manifest.json